### ISSUE TITLE
Feature request: Make it so we can show spans that encapsulating handled exception as INFO level

### ISSUE THREAD

**Issue by dmontagu** [pydantic/logfire#142] opened 2024-05-06 22:47 UTC
### Description

<img width="1501" alt="image" src="https://github.com/pydantic/logfire/assets/35119617/1216f1b4-89d3-4cfb-b659-10e988fc100f">
In this case, the outermost task did a retry of a failure, and the retry succeeded.

I think what we can do to better handle things today is, rather than showing the worst descendant level of a span in all circumstances, we do the following:
* If a span has a level explicitly set, we use that as the level to display in the UI
* If the span has level null, we look at its children (recursively over other spans with level null) for the worst level, and show that

We probably also want to make sure there is an API for late-setting the level on a span so that, e.g. in the example above, we could leave the level unset until the request finally succeeds, then set the level to INFO right at the end when we know the inner call did succeed, as a way to get the bar to show up the desired color.

@alexmojaki if you agree with this, I am happy to handle the frontend side if you can help with the SDK. If you disagree with this approach, happy to discuss (I'm not 100% confident it doesn't have issues, but it made sense to me).

(Reported by @willbakst)

**Comment by alexmojaki** [comment] 2024-05-07 11:34
Spans no longer have null levels. The backend defaults them to info.

> We probably also want to make sure there is an API for late-setting the level on a span

There's a `LogfireSpan.set_level` method already.

Personally I think the UI should have room to show both the current span level and some information about its descendant levels, e.g. an error bubble inside an info bubble or a small error bubble on the side.

**Comment by alexmojaki** [comment] 2024-05-07 16:05
> In the meantime, I'll check out the `set_level` method! Thanks!

Since spans already default to info, it sounds like you shouldn't have a need for it.

**Comment by willbakst** [comment] 2024-05-10 15:43
So the issue is that if I don't manually set anything and an error happens internally to the parent span, the parent span shows up as an error even though the error was actually handled internally (i.e. the call was retried and succeeded).

I tried using `set_level` to force the parent to be 'info', but (1) I couldn't get this working, and (2) I don't think this is actually the right approach since I do want the parent to be 'error' if none of the inner calls succeed after hitting max retries.

Any idea what approach would be best here to get the desired behavior? I'm wondering if maybe there's a better solution on the UI side as you mentioned to somehow check if the error was handled before the span finished and then display that there was a handled error within the span?

**Comment by alexmojaki** [comment] 2024-09-17 11:31
This is now resolved in the UI - the level of a span is distinguished from its descendants, and the bubble can have two colours.

**Closed by alexmojaki** 2024-09-17 11:31 UTC
Labels: Feature Request
