### ISSUE TITLE
possibility to use on-prem

### ISSUE THREAD

**Issue by fastaimldata** [pydantic/logfire#718] opened 2024-12-23 09:31 UTC
### Question

Is it possible to use logfire (atleast a prelim version) on-premises without having to authenticate?

**Comment by alexmojaki** [comment] 2024-12-23 09:53
Duplicate of https://github.com/pydantic/logfire/issues/78

To send data from logfire to an alternative backend: https://logfire.pydantic.dev/docs/how-to-guides/alternative-backends/

**Closed by alexmojaki** 2024-12-23 09:53 UTC
Labels: Question
