### ISSUE TITLE
Adding LogFire Broke Existing Uvicorn FastAPI Console Logging

### ISSUE THREAD

**Issue by JohnPeng47** [pydantic/logfire#70] opened 2024-05-01 15:44 UTC
### Description

Had existing uvicorn setup configured on debug logging config like so:
`
  uvicorn.run(
      "main:app",
      host="0.0.0.0",
      port=3000,
      reload=True,
      reload_excludes=["./repos"],
      # log_config="uvicorn.yaml",
  )
`
Default logging produces logs for every request and print statements in my app.

After following instructions and configuring logfire with my FastAPI app, I dont see ANYTHING logged to my console. 

This is ... not cool in the slightest. What turned started as a morning exploring some cool new logging alternatives now turns into me trying to debug what exactly logfire messed up in my default logging configs. Any idea guys? (Oh and btw, ofc logging works to logfire web interface ....)

**Comment by JohnPeng47** [comment] 2024-05-01 15:46
This actually. Ridiculous. Need to put some warning on your page that this will break your existing logging setup

**Comment by JohnPeng47** [comment] 2024-05-01 15:54
Tried specifying a manual logging config to uvicorn, still nothing outputted to console. Now the only way to get any logged output is by using logfire

**Comment by alexmojaki** [comment] 2024-05-01 15:58
Did you set up the standard library logging integration, i.e. something like https://docs.pydantic.dev/logfire/integrations/logging/?

Not saying that you have to, just that this is the only reason I can imagine logfire interfering with existing logging.

For good measure you could also try `logfire.configure(..., console=False)`.

**Comment by JohnPeng47** [comment] 2024-05-01 16:46
Nope do not have stdlib logging

So the really weird thing is. Even when I comment out all the logfire imports/logfire.configure/logfire.instrument_app, my uvicorn still prints nothing to console. Which is why Im wondering, do you guys write some kind of persistent config change for uvicorn during the initial logfire configure? Otherwise Im hardpressed to understand whats going on. Probably something weird happening on my side

**Comment by alexmojaki** [comment] 2024-05-01 17:10
No, the only persistent config is for authenticating with logfire.

**Comment by JohnPeng47** [comment] 2024-05-01 17:42
Yeah its very strange. Tbh Im just skirting around this issue for now and deploying on my Linux server instead. Not sure when or if I will get around to poking around. Ill leave it up to you to close or keep the issue open

**Comment by Kludex** [comment] 2024-05-02 07:13
> This actually. Ridiculous. Need to put some warning on your page that this will break your existing logging setup

We are sorry it made you disappointed. We are in beta, and things are not perfect yet, but we'll get there.

Can you perhaps try to provide us a minimal, reproducible example?

I'm not sure that it matters here, but I'm a [Uvicorn maintainer](https://github.com/Kludex). We are more than happy to help.

**Comment by Kludex** [comment] 2024-05-07 07:32
Since we can't reproduce it, I'll be closing this for the time being.

If you can provide a MRE, I'd be more than happy to reopen this issue. 🙏

**Closed by Kludex** 2024-05-07 07:32 UTC
Labels: Bug, FastAPI, Logging

**Comment by JohnPeng47** [comment] 2024-05-07 14:38
Yeah sorry, busy with other stuff, but when I circle back to logging, Ill
take a look at it again
