### ISSUE TITLE
Logging to multiple logfire project simultaneously

### ISSUE THREAD

**Issue by Mumbawa** [pydantic/logfire#493] opened 2024-10-10 21:00 UTC
### Question

Is there any mechanism to perform logging to multiple logfire project simultaneously from the same app?

To give you an example:

I have a backend service and I have an associated logfire project to this backend (my_backend_logfire_proj)... 

But for whatever reason I also want to log certain specifics events that occur in the same backend to a different logfire project.

**Comment by alexmojaki** [comment] 2024-10-11 08:37
Duplicate of https://github.com/pydantic/logfire/issues/195

**Closed** 2024-10-11 08:38 UTC
Labels: Question

**Comment by alexmojaki** [comment] 2024-10-17 16:56
@Mumbawa you can now do this using `logfire.configure(local=True)`: https://logfire.pydantic.dev/docs/reference/api/logfire/#logfire.configure(local)

**Comment by Mumbawa** [comment] 2024-10-17 17:04
Thank you!
