### ISSUE TITLE
support to protobuf >=5.0

### ISSUE THREAD

**Issue by mplemay** [pydantic/logfire#714] opened 2024-12-21 15:16 UTC
### Description

Installing `logfire` (I am using `2.9.0`) downgrades `protobuf` and `grpcio-tools`.

```
uv add 'logfire[sqlalchemy,fastapi,aiohttp]'
Resolved 236 packages in 590ms
   Built brugge @ file:///Users/matthewlemay/Github/brugge
Prepared 8 packages in 195ms
Uninstalled 13 packages in 70ms
Installed 19 packages in 24ms
 + asgiref==3.8.1
 ~ brugge==0.1.0 (from file:///Users/matthewlemay/Github/brugge)
 - grpcio-tools==1.68.1
 + grpcio-tools==1.62.3
 - hatchet-sdk==0.42.5
 + hatchet-sdk==0.42.4
 - importlib-metadata==8.5.0
 + importlib-metadata==8.4.0
 - opentelemetry-api==1.29.0
 + opentelemetry-api==1.27.0
 - opentelemetry-exporter-otlp==1.29.0
 + opentelemetry-exporter-otlp==1.27.0
 - opentelemetry-exporter-otlp-proto-common==1.29.0
 + opentelemetry-exporter-otlp-proto-common==1.27.0
 - opentelemetry-exporter-otlp-proto-grpc==1.29.0
 + opentelemetry-exporter-otlp-proto-grpc==1.27.0
 - opentelemetry-exporter-otlp-proto-http==1.29.0
 + opentelemetry-exporter-otlp-proto-http==1.27.0
 + opentelemetry-instrumentation-aiohttp-client==0.48b0
 + opentelemetry-instrumentation-asgi==0.48b0
 + opentelemetry-instrumentation-fastapi==0.48b0
 + opentelemetry-instrumentation-sqlalchemy==0.48b0
 - opentelemetry-proto==1.29.0
 + opentelemetry-proto==1.27.0
 - opentelemetry-sdk==1.29.0
 + opentelemetry-sdk==1.27.0
 - opentelemetry-semantic-conventions==0.50b0
 + opentelemetry-semantic-conventions==0.48b0
 + opentelemetry-util-http==0.48b0
 - protobuf==5.29.2
 + protobuf==4.25.5
 ```

**Comment by alexmojaki** [comment] 2024-12-21 15:25
In general it looks like it downgraded a few things, including opentelemetry packages which it definitely shouldn't. This is probably either because of some other dependency conflicting, or maybe your Python version if you're using Python 3.13?

**Comment by mplemay** [comment] 2024-12-21 15:39
@alexmojaki Thanks for the prompt response. My python version is locked to `requires-python = ">=3.12,<3.13"`, so that could very well be the cause. Even still `3.12` is a pretty recent version of python so it should be supported. Previously, I had only installed `logfire` without the `sqlalchemy,fastapi,aiohttp` extras, so my hunch would be that one of the transitive (ex: opentelemtry) dependencies caused the downgrade. Do you know off-hand if a way to why the version was chosen by `uv`?

**Comment by alexmojaki** [comment] 2024-12-21 16:13
Python 3.12 should be fine. Try installing one extra at a time?

**Comment by Kludex** [comment] 2024-12-23 13:41
It's the `0.48b0`, you need to bump the `opentelemetry-instrumentation` related packages to `0.50b0`.

I reproduced with:
```bash
❯ uv add 'logfire[sqlalchemy,fastapi,aiohttp]' opentelemetry-instrumentation-aiohttp-client==0.48b0
```

**Comment by Kludex** [comment] 2024-12-24 08:06
@mplemay Given my previous answer, I'll be closing this issue.

Please let me know if that doesn't solve your case, and we can reopen.

**Closed by Kludex** 2024-12-24 08:06 UTC
Labels: Feature Request

**Comment by mplemay** [comment] 2024-12-25 02:33
@Kludex Thanks for your response. You were right. The version locking shenanigans was due to a downstream dependency.

Happy Holidays!

**Comment by Kludex** [comment] 2024-12-25 08:12
To you too! 😁
