### ISSUE TITLE
Setting up Multi environment (local + production)

### ISSUE THREAD

**Issue by ddahan** [pydantic/logfire#455] opened 2024-09-27 09:58 UTC
### Question

Hi there,

First of all, congratulations on this new project! It's very exciting after just a few minutes of use.

In fact, it's so exciting that I’m considering replacing [Debug Toolbar](https://github.com/mongkok/fastapi-debug-toolbar) for my FastAPI project. However, I then asked myself:

Is Logfire intended to replace tools like this for local environments? What would I gain or lose? For example, when Logfire is no longer free, I assume running it in a local environment could become expensive?

How do I split and sandbox environments? Should I simply create two projects (myproj-local and myproj-prod)?

I'm eager to hear your guidance on this.

Thanks, and keep up the great work!

**Comment by Kludex** [comment] 2024-09-30 13:19
> Should I simply create two projects (myproj-local and myproj-prod)?

Yes. That's the idea for now.

We are planning on making it easy to have multiple environments in a single project.

**Comment by ddahan** [comment] 2024-10-01 08:12
@Kludex thanks for the answer. What do you think about the other question: the ability to replace a local debug tool with LogFire? The purpose would be to have the same experience in local and in production.

**Comment by Kludex** [comment] 2024-10-01 08:44
> [...] when Logfire is no longer free, I assume running it in a local environment could become expensive?

We still give 10m spans/metrics free monthly, which should be more than enough to cover any expenses that come from the local development.

> [...] the ability to replace a local debug tool with LogFire?

Yes! That's the intention.

**Comment by sydney-runkle** [comment] 2024-10-11 22:52
@Kludex, can we close this as a duplicate of https://github.com/pydantic/logfire/issues/319?

**Closed** 2024-10-12 01:08 UTC
Labels: Question
