### ISSUE TITLE
Specifying `http_client` in openai client options causing `TypeError` with `instrument_httpx`

### ISSUE THREAD

**Issue by CNSeniorious000** [pydantic/logfire#264] opened 2024-06-14 12:09 UTC
### Description

If I use `instrument_httpx()`, and then construct an OpenAI client with a custom httpx client, openai will raise an TypeError:

```py
TypeError: Invalid `http_client` argument; Expected an instance of `httpx.AsyncClient` but got <class 'httpx.AsyncClient'>
```

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="0.42.0"
platform="Windows-10-10.0.22631-SP0"
python="3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]"
[related_packages]
requests="2.32.3"
pydantic="2.7.4"
openai="1.34.0"
protobuf="4.25.3"
rich="13.7.1"
executing="2.0.1"
opentelemetry-api="1.25.0"
opentelemetry-exporter-otlp-proto-common="1.25.0"
opentelemetry-exporter-otlp-proto-http="1.25.0"
opentelemetry-instrumentation="0.46b0"
opentelemetry-instrumentation-asgi="0.46b0"
opentelemetry-instrumentation-fastapi="0.46b0"
opentelemetry-instrumentation-httpx="0.46b0"
opentelemetry-instrumentation-system-metrics="0.46b0"
opentelemetry-proto="1.25.0"
opentelemetry-sdk="1.25.0"
opentelemetry-semantic-conventions="0.46b0"
opentelemetry-util-http="0.46b0"
```

**Comment by alexmojaki** [comment] 2024-06-14 12:43
I can reproduce with this code:

```python
import httpx
import openai

import logfire

logfire.configure()

client = httpx.AsyncClient()
logfire.instrument_httpx()
openai.AsyncClient(http_client=client, api_key='...')
```

The error doesn't happen if `client = httpx.AsyncClient()` is done after `logfire.instrument_httpx()`. What's happening is that `logfire.instrument_httpx` replaces the class `httpx.AsyncClient` with its own subclass, so when openai checks `isinstance(http_client, httpx.AsyncClient)` it fails because now `http_client` is an instance of the original class while `httpx.AsyncClient` is a subclass of the original.

This should be reported to OTEL.

**Comment by CNSeniorious000** [comment] 2024-06-14 12:53
I see. Thanks for your clear explanation. I should instrument_httpx after any httpx instance initialized. But maybe I think OTEL can't instrument httpx without subclassing it?

**Comment by alexmojaki** [comment] 2024-06-14 14:19
No, you should call `instrument_httpx` before constructing the client. In fact you should do that anyway if you want the client to be instrumented.

OTEL could instrument httpx without subclassing, e.g. by patching the `__init__` method on the original class.

**Comment by CNSeniorious000** [comment] 2024-06-14 14:32
Yeah thanks. I made a typos mistake.

I've refactored my code and openai works well with httpx now. I am going to post an issue to OTEL now. Thanks for your reproduction example

**Comment by Kludex** [comment] 2024-07-18 07:02
Thanks for creating the issue on OTel side.

For people with the same problem, you can watch this issue: https://github.com/open-telemetry/opentelemetry-python-contrib/issues/2609.

Since it's on their side, I'll be closing this. 🙏

**Closed by Kludex** 2024-07-18 07:02 UTC
Labels: Bug, OTel Issue
